site_name: Admin Guide

pages:
- Home: 'index.md'
- 'Build from sources': 'build_source.md'
- 'Running Orion from command line': 'cli.md'
- 'Database administration': 'database_admin.md'
- 'Logs': 'logs.md'
- 'Watchdog': 'watchdog.md'
- 'Diagnosis': 'diagnosis.md'
- 'Rush relayer': 'rush.md'
- 'Management REST interface': 'management_api.md'
- 'Data model': 'database_model.md'
- 'Resources & I/O flows': 'resources.md'
- 'Upgrading from previous to 0.14.1': 'upgrading_crossing_0-14-1.md'
- 'Upgrading from previous to 0.19.0': 'upgrading_crossing_0-19-0.md'
- 'Upgrading from previous to 0.21.0': 'upgrading_crossing_0-21-0.md'
