site_name: FIWARE Policy Manager

pages:
- Home: 'README.rst'
- User and Programmers Guide: 'user_guide.rst'
- Installation and Administration Guide: 'admin_guide.rst'
- Open RESTful API Specification: 'open_spec.rst'
- Architecture Description: 'architecture.rst'

